// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf.Animal;

public interface AnimalProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 registrationNumber = 1;</code>
   * @return The registrationNumber.
   */
  long getRegistrationNumber();

  /**
   * <code>int32 weight = 2;</code>
   * @return The weight.
   */
  int getWeight();

  /**
   * <code>string arrivalDate = 3;</code>
   * @return The arrivalDate.
   */
  java.lang.String getArrivalDate();
  /**
   * <code>string arrivalDate = 3;</code>
   * @return The bytes for arrivalDate.
   */
  com.google.protobuf.ByteString
      getArrivalDateBytes();

  /**
   * <code>string origin = 4;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 4;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>string type = 5;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 5;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
