// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf.Animal;

public interface AnimalListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  java.util.List<AnimalProto>
      getAllAnimalsList();
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  AnimalProto getAllAnimals(int index);
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  int getAllAnimalsCount();
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  java.util.List<? extends AnimalProtoOrBuilder>
      getAllAnimalsOrBuilderList();
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  AnimalProtoOrBuilder getAllAnimalsOrBuilder(
      int index);

  /**
   * <code>int64 code = 2;</code>
   * @return The code.
   */
  long getCode();
}
