// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf.Animal;

/**
 * Protobuf type {@code AnimalListProto}
 */
public final class AnimalListProto extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:AnimalListProto)
        AnimalListProtoOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use AnimalListProto.newBuilder() to construct.
    private AnimalListProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AnimalListProto() {
        allAnimals_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new AnimalListProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private AnimalListProto(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            allAnimals_ = new java.util.ArrayList<AnimalProto>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        allAnimals_.add(
                                input.readMessage(AnimalProto.parser(), extensionRegistry));
                        break;
                    }
                    case 16: {

                        code_ = input.readInt64();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                allAnimals_ = java.util.Collections.unmodifiableList(allAnimals_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Animal.internal_static_AnimalListProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Animal.internal_static_AnimalListProto_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        AnimalListProto.class, AnimalListProto.Builder.class);
    }

    public static final int ALLANIMALS_FIELD_NUMBER = 1;
    private java.util.List<AnimalProto> allAnimals_;

    /**
     * <code>repeated .AnimalProto allAnimals = 1;</code>
     */
    @java.lang.Override
    public java.util.List<AnimalProto> getAllAnimalsList() {
        return allAnimals_;
    }

    /**
     * <code>repeated .AnimalProto allAnimals = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends AnimalProtoOrBuilder>
    getAllAnimalsOrBuilderList() {
        return allAnimals_;
    }

    /**
     * <code>repeated .AnimalProto allAnimals = 1;</code>
     */
    @java.lang.Override
    public int getAllAnimalsCount() {
        return allAnimals_.size();
    }

    /**
     * <code>repeated .AnimalProto allAnimals = 1;</code>
     */
    @java.lang.Override
    public AnimalProto getAllAnimals(int index) {
        return allAnimals_.get(index);
    }

    /**
     * <code>repeated .AnimalProto allAnimals = 1;</code>
     */
    @java.lang.Override
    public AnimalProtoOrBuilder getAllAnimalsOrBuilder(
            int index) {
        return allAnimals_.get(index);
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private long code_;

    /**
     * <code>int64 code = 2;</code>
     *
     * @return The code.
     */
    @java.lang.Override
    public long getCode() {
        return code_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < allAnimals_.size(); i++) {
            output.writeMessage(1, allAnimals_.get(i));
        }
        if (code_ != 0L) {
            output.writeInt64(2, code_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < allAnimals_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, allAnimals_.get(i));
        }
        if (code_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(2, code_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof AnimalListProto)) {
            return super.equals(obj);
        }
        AnimalListProto other = (AnimalListProto) obj;

        if (!getAllAnimalsList()
                .equals(other.getAllAnimalsList())) return false;
        if (getCode()
                != other.getCode()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getAllAnimalsCount() > 0) {
            hash = (37 * hash) + ALLANIMALS_FIELD_NUMBER;
            hash = (53 * hash) + getAllAnimalsList().hashCode();
        }
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getCode());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static AnimalListProto parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static AnimalListProto parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static AnimalListProto parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static AnimalListProto parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static AnimalListProto parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static AnimalListProto parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static AnimalListProto parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static AnimalListProto parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static AnimalListProto parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static AnimalListProto parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static AnimalListProto parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static AnimalListProto parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(AnimalListProto prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code AnimalListProto}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:AnimalListProto)
            AnimalListProtoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Animal.internal_static_AnimalListProto_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Animal.internal_static_AnimalListProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            AnimalListProto.class, AnimalListProto.Builder.class);
        }

        // Construct using slaughterHouse.grpc.protobuf.Animal.AnimalListProto.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getAllAnimalsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (allAnimalsBuilder_ == null) {
                allAnimals_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                allAnimalsBuilder_.clear();
            }
            code_ = 0L;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Animal.internal_static_AnimalListProto_descriptor;
        }

        @java.lang.Override
        public AnimalListProto getDefaultInstanceForType() {
            return AnimalListProto.getDefaultInstance();
        }

        @java.lang.Override
        public AnimalListProto build() {
            AnimalListProto result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public AnimalListProto buildPartial() {
            AnimalListProto result = new AnimalListProto(this);
            int from_bitField0_ = bitField0_;
            if (allAnimalsBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    allAnimals_ = java.util.Collections.unmodifiableList(allAnimals_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.allAnimals_ = allAnimals_;
            } else {
                result.allAnimals_ = allAnimalsBuilder_.build();
            }
            result.code_ = code_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof AnimalListProto) {
                return mergeFrom((AnimalListProto) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(AnimalListProto other) {
            if (other == AnimalListProto.getDefaultInstance()) return this;
            if (allAnimalsBuilder_ == null) {
                if (!other.allAnimals_.isEmpty()) {
                    if (allAnimals_.isEmpty()) {
                        allAnimals_ = other.allAnimals_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureAllAnimalsIsMutable();
                        allAnimals_.addAll(other.allAnimals_);
                    }
                    onChanged();
                }
            } else {
                if (!other.allAnimals_.isEmpty()) {
                    if (allAnimalsBuilder_.isEmpty()) {
                        allAnimalsBuilder_.dispose();
                        allAnimalsBuilder_ = null;
                        allAnimals_ = other.allAnimals_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        allAnimalsBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getAllAnimalsFieldBuilder() : null;
                    } else {
                        allAnimalsBuilder_.addAllMessages(other.allAnimals_);
                    }
                }
            }
            if (other.getCode() != 0L) {
                setCode(other.getCode());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            AnimalListProto parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (AnimalListProto) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<AnimalProto> allAnimals_ =
                java.util.Collections.emptyList();

        private void ensureAllAnimalsIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                allAnimals_ = new java.util.ArrayList<AnimalProto>(allAnimals_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                AnimalProto, AnimalProto.Builder, AnimalProtoOrBuilder> allAnimalsBuilder_;

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public java.util.List<AnimalProto> getAllAnimalsList() {
            if (allAnimalsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(allAnimals_);
            } else {
                return allAnimalsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public int getAllAnimalsCount() {
            if (allAnimalsBuilder_ == null) {
                return allAnimals_.size();
            } else {
                return allAnimalsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public AnimalProto getAllAnimals(int index) {
            if (allAnimalsBuilder_ == null) {
                return allAnimals_.get(index);
            } else {
                return allAnimalsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder setAllAnimals(
                int index, AnimalProto value) {
            if (allAnimalsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAllAnimalsIsMutable();
                allAnimals_.set(index, value);
                onChanged();
            } else {
                allAnimalsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder setAllAnimals(
                int index, AnimalProto.Builder builderForValue) {
            if (allAnimalsBuilder_ == null) {
                ensureAllAnimalsIsMutable();
                allAnimals_.set(index, builderForValue.build());
                onChanged();
            } else {
                allAnimalsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder addAllAnimals(AnimalProto value) {
            if (allAnimalsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAllAnimalsIsMutable();
                allAnimals_.add(value);
                onChanged();
            } else {
                allAnimalsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder addAllAnimals(
                int index, AnimalProto value) {
            if (allAnimalsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAllAnimalsIsMutable();
                allAnimals_.add(index, value);
                onChanged();
            } else {
                allAnimalsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder addAllAnimals(
                AnimalProto.Builder builderForValue) {
            if (allAnimalsBuilder_ == null) {
                ensureAllAnimalsIsMutable();
                allAnimals_.add(builderForValue.build());
                onChanged();
            } else {
                allAnimalsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder addAllAnimals(
                int index, AnimalProto.Builder builderForValue) {
            if (allAnimalsBuilder_ == null) {
                ensureAllAnimalsIsMutable();
                allAnimals_.add(index, builderForValue.build());
                onChanged();
            } else {
                allAnimalsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder addAllAllAnimals(
                java.lang.Iterable<? extends AnimalProto> values) {
            if (allAnimalsBuilder_ == null) {
                ensureAllAnimalsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, allAnimals_);
                onChanged();
            } else {
                allAnimalsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder clearAllAnimals() {
            if (allAnimalsBuilder_ == null) {
                allAnimals_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                allAnimalsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public Builder removeAllAnimals(int index) {
            if (allAnimalsBuilder_ == null) {
                ensureAllAnimalsIsMutable();
                allAnimals_.remove(index);
                onChanged();
            } else {
                allAnimalsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public AnimalProto.Builder getAllAnimalsBuilder(
                int index) {
            return getAllAnimalsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public AnimalProtoOrBuilder getAllAnimalsOrBuilder(
                int index) {
            if (allAnimalsBuilder_ == null) {
                return allAnimals_.get(index);
            } else {
                return allAnimalsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public java.util.List<? extends AnimalProtoOrBuilder>
        getAllAnimalsOrBuilderList() {
            if (allAnimalsBuilder_ != null) {
                return allAnimalsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(allAnimals_);
            }
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public AnimalProto.Builder addAllAnimalsBuilder() {
            return getAllAnimalsFieldBuilder().addBuilder(
                    AnimalProto.getDefaultInstance());
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public AnimalProto.Builder addAllAnimalsBuilder(
                int index) {
            return getAllAnimalsFieldBuilder().addBuilder(
                    index, AnimalProto.getDefaultInstance());
        }

        /**
         * <code>repeated .AnimalProto allAnimals = 1;</code>
         */
        public java.util.List<AnimalProto.Builder>
        getAllAnimalsBuilderList() {
            return getAllAnimalsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                AnimalProto, AnimalProto.Builder, AnimalProtoOrBuilder>
        getAllAnimalsFieldBuilder() {
            if (allAnimalsBuilder_ == null) {
                allAnimalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        AnimalProto, AnimalProto.Builder, AnimalProtoOrBuilder>(
                        allAnimals_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                allAnimals_ = null;
            }
            return allAnimalsBuilder_;
        }

        private long code_;

        /**
         * <code>int64 code = 2;</code>
         *
         * @return The code.
         */
        @java.lang.Override
        public long getCode() {
            return code_;
        }

        /**
         * <code>int64 code = 2;</code>
         *
         * @param value The code to set.
         * @return This builder for chaining.
         */
        public Builder setCode(long value) {

            code_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 code = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCode() {

            code_ = 0L;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:AnimalListProto)
    }

    // @@protoc_insertion_point(class_scope:AnimalListProto)
    private static final AnimalListProto DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new AnimalListProto();
    }

    public static AnimalListProto getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnimalListProto>
            PARSER = new com.google.protobuf.AbstractParser<AnimalListProto>() {
        @java.lang.Override
        public AnimalListProto parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new AnimalListProto(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<AnimalListProto> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnimalListProto> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public AnimalListProto getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

