// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf;

public final class Animal {
  private Animal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalListProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_id_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_id_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_origin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_origin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_type_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_type_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_date_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_date_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014animal.proto\"A\n\017AnimalListProto\022 \n\nall" +
      "Animals\030\001 \003(\0132\014.AnimalProto\022\014\n\004code\030\002 \001(" +
      "\003\" \n\002id\022\032\n\022registrationNumber\030\001 \001(\t\"\007\n\005e" +
      "mpty\"\030\n\006origin\022\016\n\006origin\030\001 \001(\t\"\024\n\004type\022\014" +
      "\n\004type\030\001 \001(\t\"\024\n\004date\022\014\n\004date\030\001 \001(\t\"l\n\013An" +
      "imalProto\022\032\n\022registrationNumber\030\001 \001(\003\022\016\n" +
      "\006weight\030\002 \001(\005\022\023\n\013arrivalDate\030\003 \001(\t\022\016\n\006or" +
      "igin\030\004 \001(\t\022\014\n\004type\030\005 \001(\t2\370\001\n\rAnimalServi" +
      "ce\022%\n\016findAnimalById\022\003.id\032\014.AnimalProto\"" +
      "\000\022,\n\016findAllAnimals\022\006.empty\032\020.AnimalList" +
      "Proto\"\000\0222\n\023findAnimalsByOrigin\022\007.origin\032" +
      "\020.AnimalListProto\"\000\022.\n\021findAnimalsByType" +
      "\022\005.type\032\020.AnimalListProto\"\000\022.\n\021findAnima" +
      "lsByDate\022\005.date\032\020.AnimalListProto\"\000B \n\034s" +
      "laughterHouse.grpc.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AnimalListProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimalListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalListProto_descriptor,
        new java.lang.String[] { "AllAnimals", "Code", });
    internal_static_id_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_id_descriptor,
        new java.lang.String[] { "RegistrationNumber", });
    internal_static_empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_empty_descriptor,
        new java.lang.String[] { });
    internal_static_origin_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_origin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_origin_descriptor,
        new java.lang.String[] { "Origin", });
    internal_static_type_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_type_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_date_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_date_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_AnimalProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AnimalProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalProto_descriptor,
        new java.lang.String[] { "RegistrationNumber", "Weight", "ArrivalDate", "Origin", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
