// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf;

public interface AnimalListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  java.util.List<slaughterHouse.grpc.protobuf.AnimalProto> 
      getAllAnimalsList();
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  slaughterHouse.grpc.protobuf.AnimalProto getAllAnimals(int index);
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  int getAllAnimalsCount();
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  java.util.List<? extends slaughterHouse.grpc.protobuf.AnimalProtoOrBuilder> 
      getAllAnimalsOrBuilderList();
  /**
   * <code>repeated .AnimalProto allAnimals = 1;</code>
   */
  slaughterHouse.grpc.protobuf.AnimalProtoOrBuilder getAllAnimalsOrBuilder(
      int index);

  /**
   * <code>int64 code = 2;</code>
   * @return The code.
   */
  long getCode();
}
