// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:empty)
    com.google.protobuf.MessageOrBuilder {
}
