// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf;

public interface idOrBuilder extends
    // @@protoc_insertion_point(interface_extends:id)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string registrationNumber = 1;</code>
   * @return The registrationNumber.
   */
  java.lang.String getRegistrationNumber();
  /**
   * <code>string registrationNumber = 1;</code>
   * @return The bytes for registrationNumber.
   */
  com.google.protobuf.ByteString
      getRegistrationNumberBytes();
}
