// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf;

public interface originOrBuilder extends
    // @@protoc_insertion_point(interface_extends:origin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string origin = 1;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 1;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();
}
