// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package slaughterHouse.grpc.protobuf.product;

public interface ProductProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 productId = 1;</code>
   */
  long getProductId();

  /**
   * <code>optional .google.protobuf.StringValue productType = 2;</code>
   */
  boolean hasProductType();
  /**
   * <code>optional .google.protobuf.StringValue productType = 2;</code>
   */
  com.google.protobuf.StringValue getProductType();
  /**
   * <code>optional .google.protobuf.StringValue productType = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getProductTypeOrBuilder();

  /**
   * <code>optional int32 productWeight = 3;</code>
   */
  int getProductWeight();

  /**
   * <code>repeated .AnimalListProto involvedAnimals = 4;</code>
   */
  java.util.List<slaughterHouse.grpc.protobuf.animals.AnimalListProto> 
      getInvolvedAnimalsList();
  /**
   * <code>repeated .AnimalListProto involvedAnimals = 4;</code>
   */
  slaughterHouse.grpc.protobuf.animals.AnimalListProto getInvolvedAnimals(int index);
  /**
   * <code>repeated .AnimalListProto involvedAnimals = 4;</code>
   */
  int getInvolvedAnimalsCount();
  /**
   * <code>repeated .AnimalListProto involvedAnimals = 4;</code>
   */
  java.util.List<? extends slaughterHouse.grpc.protobuf.animals.AnimalListProtoOrBuilder> 
      getInvolvedAnimalsOrBuilderList();
  /**
   * <code>repeated .AnimalListProto involvedAnimals = 4;</code>
   */
  slaughterHouse.grpc.protobuf.animals.AnimalListProtoOrBuilder getInvolvedAnimalsOrBuilder(
      int index);
}
