// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package slaughterHouse.grpc.protobuf.product;

/**
 * Protobuf type {@code ProductListProto}
 */
public  final class ProductListProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProductListProto)
    ProductListProtoOrBuilder {
  // Use ProductListProto.newBuilder() to construct.
  private ProductListProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductListProto() {
    allProducts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProductListProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              allProducts_ = new java.util.ArrayList<slaughterHouse.grpc.protobuf.product.ProductProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            allProducts_.add(
                input.readMessage(slaughterHouse.grpc.protobuf.product.ProductProto.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        allProducts_ = java.util.Collections.unmodifiableList(allProducts_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return slaughterHouse.grpc.protobuf.product.Products.internal_static_ProductListProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return slaughterHouse.grpc.protobuf.product.Products.internal_static_ProductListProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            slaughterHouse.grpc.protobuf.product.ProductListProto.class, slaughterHouse.grpc.protobuf.product.ProductListProto.Builder.class);
  }

  public static final int ALLPRODUCTS_FIELD_NUMBER = 1;
  private java.util.List<slaughterHouse.grpc.protobuf.product.ProductProto> allProducts_;
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  public java.util.List<slaughterHouse.grpc.protobuf.product.ProductProto> getAllProductsList() {
    return allProducts_;
  }
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  public java.util.List<? extends slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder> 
      getAllProductsOrBuilderList() {
    return allProducts_;
  }
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  public int getAllProductsCount() {
    return allProducts_.size();
  }
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  public slaughterHouse.grpc.protobuf.product.ProductProto getAllProducts(int index) {
    return allProducts_.get(index);
  }
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  public slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder getAllProductsOrBuilder(
      int index) {
    return allProducts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < allProducts_.size(); i++) {
      output.writeMessage(1, allProducts_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < allProducts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, allProducts_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof slaughterHouse.grpc.protobuf.product.ProductListProto)) {
      return super.equals(obj);
    }
    slaughterHouse.grpc.protobuf.product.ProductListProto other = (slaughterHouse.grpc.protobuf.product.ProductListProto) obj;

    boolean result = true;
    result = result && getAllProductsList()
        .equals(other.getAllProductsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getAllProductsCount() > 0) {
      hash = (37 * hash) + ALLPRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getAllProductsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static slaughterHouse.grpc.protobuf.product.ProductListProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(slaughterHouse.grpc.protobuf.product.ProductListProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductListProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProductListProto)
      slaughterHouse.grpc.protobuf.product.ProductListProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return slaughterHouse.grpc.protobuf.product.Products.internal_static_ProductListProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return slaughterHouse.grpc.protobuf.product.Products.internal_static_ProductListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              slaughterHouse.grpc.protobuf.product.ProductListProto.class, slaughterHouse.grpc.protobuf.product.ProductListProto.Builder.class);
    }

    // Construct using slaughterHouse.grpc.protobuf.product.ProductListProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAllProductsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (allProductsBuilder_ == null) {
        allProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        allProductsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return slaughterHouse.grpc.protobuf.product.Products.internal_static_ProductListProto_descriptor;
    }

    public slaughterHouse.grpc.protobuf.product.ProductListProto getDefaultInstanceForType() {
      return slaughterHouse.grpc.protobuf.product.ProductListProto.getDefaultInstance();
    }

    public slaughterHouse.grpc.protobuf.product.ProductListProto build() {
      slaughterHouse.grpc.protobuf.product.ProductListProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public slaughterHouse.grpc.protobuf.product.ProductListProto buildPartial() {
      slaughterHouse.grpc.protobuf.product.ProductListProto result = new slaughterHouse.grpc.protobuf.product.ProductListProto(this);
      int from_bitField0_ = bitField0_;
      if (allProductsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          allProducts_ = java.util.Collections.unmodifiableList(allProducts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.allProducts_ = allProducts_;
      } else {
        result.allProducts_ = allProductsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof slaughterHouse.grpc.protobuf.product.ProductListProto) {
        return mergeFrom((slaughterHouse.grpc.protobuf.product.ProductListProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(slaughterHouse.grpc.protobuf.product.ProductListProto other) {
      if (other == slaughterHouse.grpc.protobuf.product.ProductListProto.getDefaultInstance()) return this;
      if (allProductsBuilder_ == null) {
        if (!other.allProducts_.isEmpty()) {
          if (allProducts_.isEmpty()) {
            allProducts_ = other.allProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAllProductsIsMutable();
            allProducts_.addAll(other.allProducts_);
          }
          onChanged();
        }
      } else {
        if (!other.allProducts_.isEmpty()) {
          if (allProductsBuilder_.isEmpty()) {
            allProductsBuilder_.dispose();
            allProductsBuilder_ = null;
            allProducts_ = other.allProducts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            allProductsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAllProductsFieldBuilder() : null;
          } else {
            allProductsBuilder_.addAllMessages(other.allProducts_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      slaughterHouse.grpc.protobuf.product.ProductListProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (slaughterHouse.grpc.protobuf.product.ProductListProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<slaughterHouse.grpc.protobuf.product.ProductProto> allProducts_ =
      java.util.Collections.emptyList();
    private void ensureAllProductsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        allProducts_ = new java.util.ArrayList<slaughterHouse.grpc.protobuf.product.ProductProto>(allProducts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        slaughterHouse.grpc.protobuf.product.ProductProto, slaughterHouse.grpc.protobuf.product.ProductProto.Builder, slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder> allProductsBuilder_;

    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public java.util.List<slaughterHouse.grpc.protobuf.product.ProductProto> getAllProductsList() {
      if (allProductsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(allProducts_);
      } else {
        return allProductsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public int getAllProductsCount() {
      if (allProductsBuilder_ == null) {
        return allProducts_.size();
      } else {
        return allProductsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public slaughterHouse.grpc.protobuf.product.ProductProto getAllProducts(int index) {
      if (allProductsBuilder_ == null) {
        return allProducts_.get(index);
      } else {
        return allProductsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder setAllProducts(
        int index, slaughterHouse.grpc.protobuf.product.ProductProto value) {
      if (allProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllProductsIsMutable();
        allProducts_.set(index, value);
        onChanged();
      } else {
        allProductsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder setAllProducts(
        int index, slaughterHouse.grpc.protobuf.product.ProductProto.Builder builderForValue) {
      if (allProductsBuilder_ == null) {
        ensureAllProductsIsMutable();
        allProducts_.set(index, builderForValue.build());
        onChanged();
      } else {
        allProductsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder addAllProducts(slaughterHouse.grpc.protobuf.product.ProductProto value) {
      if (allProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllProductsIsMutable();
        allProducts_.add(value);
        onChanged();
      } else {
        allProductsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder addAllProducts(
        int index, slaughterHouse.grpc.protobuf.product.ProductProto value) {
      if (allProductsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllProductsIsMutable();
        allProducts_.add(index, value);
        onChanged();
      } else {
        allProductsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder addAllProducts(
        slaughterHouse.grpc.protobuf.product.ProductProto.Builder builderForValue) {
      if (allProductsBuilder_ == null) {
        ensureAllProductsIsMutable();
        allProducts_.add(builderForValue.build());
        onChanged();
      } else {
        allProductsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder addAllProducts(
        int index, slaughterHouse.grpc.protobuf.product.ProductProto.Builder builderForValue) {
      if (allProductsBuilder_ == null) {
        ensureAllProductsIsMutable();
        allProducts_.add(index, builderForValue.build());
        onChanged();
      } else {
        allProductsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder addAllAllProducts(
        java.lang.Iterable<? extends slaughterHouse.grpc.protobuf.product.ProductProto> values) {
      if (allProductsBuilder_ == null) {
        ensureAllProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, allProducts_);
        onChanged();
      } else {
        allProductsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder clearAllProducts() {
      if (allProductsBuilder_ == null) {
        allProducts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        allProductsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public Builder removeAllProducts(int index) {
      if (allProductsBuilder_ == null) {
        ensureAllProductsIsMutable();
        allProducts_.remove(index);
        onChanged();
      } else {
        allProductsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public slaughterHouse.grpc.protobuf.product.ProductProto.Builder getAllProductsBuilder(
        int index) {
      return getAllProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder getAllProductsOrBuilder(
        int index) {
      if (allProductsBuilder_ == null) {
        return allProducts_.get(index);  } else {
        return allProductsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public java.util.List<? extends slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder> 
         getAllProductsOrBuilderList() {
      if (allProductsBuilder_ != null) {
        return allProductsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(allProducts_);
      }
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public slaughterHouse.grpc.protobuf.product.ProductProto.Builder addAllProductsBuilder() {
      return getAllProductsFieldBuilder().addBuilder(
          slaughterHouse.grpc.protobuf.product.ProductProto.getDefaultInstance());
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public slaughterHouse.grpc.protobuf.product.ProductProto.Builder addAllProductsBuilder(
        int index) {
      return getAllProductsFieldBuilder().addBuilder(
          index, slaughterHouse.grpc.protobuf.product.ProductProto.getDefaultInstance());
    }
    /**
     * <code>repeated .ProductProto allProducts = 1;</code>
     */
    public java.util.List<slaughterHouse.grpc.protobuf.product.ProductProto.Builder> 
         getAllProductsBuilderList() {
      return getAllProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        slaughterHouse.grpc.protobuf.product.ProductProto, slaughterHouse.grpc.protobuf.product.ProductProto.Builder, slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder> 
        getAllProductsFieldBuilder() {
      if (allProductsBuilder_ == null) {
        allProductsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            slaughterHouse.grpc.protobuf.product.ProductProto, slaughterHouse.grpc.protobuf.product.ProductProto.Builder, slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder>(
                allProducts_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        allProducts_ = null;
      }
      return allProductsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ProductListProto)
  }

  // @@protoc_insertion_point(class_scope:ProductListProto)
  private static final slaughterHouse.grpc.protobuf.product.ProductListProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new slaughterHouse.grpc.protobuf.product.ProductListProto();
  }

  public static slaughterHouse.grpc.protobuf.product.ProductListProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductListProto>
      PARSER = new com.google.protobuf.AbstractParser<ProductListProto>() {
    public ProductListProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductListProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductListProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductListProto> getParserForType() {
    return PARSER;
  }

  public slaughterHouse.grpc.protobuf.product.ProductListProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

