// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package slaughterHouse.grpc.protobuf.product;

public final class Products {
  private Products() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016products.proto\032\033google/protobuf/empty." +
      "proto\032\036google/protobuf/wrappers.proto\032\014a" +
      "nimal.proto\"\226\001\n\014ProductProto\022\021\n\tproductI" +
      "d\030\001 \001(\003\0221\n\013productType\030\002 \001(\0132\034.google.pr" +
      "otobuf.StringValue\022\025\n\rproductWeight\030\003 \001(" +
      "\005\022)\n\017involvedAnimals\030\004 \001(\0132\020.AnimalListP" +
      "roto\"6\n\020ProductListProto\022\"\n\013allProducts\030" +
      "\001 \003(\0132\r.ProductProto2\332\003\n\017ProductsService" +
      "\022-\n\rcreateProduct\022\r.ProductProto\032\r.Produ" +
      "ctProto\022=\n\017findProductById\022\033.google.prot",
      "obuf.Int64Value\032\r.ProductProto\022<\n\017findAl" +
      "lProducts\022\026.google.protobuf.Empty\032\021.Prod" +
      "uctListProto\022E\n\022findProductsByType\022\034.goo" +
      "gle.protobuf.StringValue\032\021.ProductListPr" +
      "oto\022M\n\034findAnimalsInvolvedInProduct\022\033.go" +
      "ogle.protobuf.Int64Value\032\020.AnimalListPro" +
      "to\022H\n\rdeleteProduct\022\033.google.protobuf.In" +
      "t64Value\032\032.google.protobuf.BoolValue\022;\n\r" +
      "updateProduct\022\033.google.protobuf.Int64Val" +
      "ue\032\r.ProductProtoB(\n$slaughterHouse.grpc",
      ".protobuf.productP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          slaughterHouse.grpc.protobuf.animals.Animal.getDescriptor(),
        }, assigner);
    internal_static_ProductProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductProto_descriptor,
        new java.lang.String[] { "ProductId", "ProductType", "ProductWeight", "InvolvedAnimals", });
    internal_static_ProductListProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProductListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductListProto_descriptor,
        new java.lang.String[] { "AllProducts", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    slaughterHouse.grpc.protobuf.animals.Animal.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
