// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package slaughterHouse.grpc.protobuf.product;

public interface ProductListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  java.util.List<slaughterHouse.grpc.protobuf.product.ProductProto> 
      getAllProductsList();
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  slaughterHouse.grpc.protobuf.product.ProductProto getAllProducts(int index);
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  int getAllProductsCount();
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  java.util.List<? extends slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder> 
      getAllProductsOrBuilderList();
  /**
   * <code>repeated .ProductProto allProducts = 1;</code>
   */
  slaughterHouse.grpc.protobuf.product.ProductProtoOrBuilder getAllProductsOrBuilder(
      int index);
}
