// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: products.proto

package slaughterHouse.grpc.protobuf.product;

public interface ProductProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 productId = 1;</code>
   */
  long getProductId();

  /**
   * <code>optional .google.protobuf.StringValue productType = 2;</code>
   */
  boolean hasProductType();
  /**
   * <code>optional .google.protobuf.StringValue productType = 2;</code>
   */
  com.google.protobuf.StringValue getProductType();
  /**
   * <code>optional .google.protobuf.StringValue productType = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getProductTypeOrBuilder();

  /**
   * <code>optional int32 productWeight = 3;</code>
   */
  int getProductWeight();

  /**
   * <code>optional .AnimalListProto involvedAnimals = 4;</code>
   */
  boolean hasInvolvedAnimals();
  /**
   * <code>optional .AnimalListProto involvedAnimals = 4;</code>
   */
  slaughterHouse.grpc.protobuf.animals.AnimalListProto getInvolvedAnimals();
  /**
   * <code>optional .AnimalListProto involvedAnimals = 4;</code>
   */
  slaughterHouse.grpc.protobuf.animals.AnimalListProtoOrBuilder getInvolvedAnimalsOrBuilder();
}
