// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf.animals;

public final class Animal {
  private Animal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalListProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014animal.proto\032\033google/protobuf/empty.pr" +
      "oto\032\036google/protobuf/wrappers.proto\"A\n\017A" +
      "nimalListProto\022 \n\nallAnimals\030\001 \003(\0132\014.Ani" +
      "malProto\022\014\n\004code\030\002 \001(\003\"l\n\013AnimalProto\022\032\n" +
      "\022registrationNumber\030\001 \001(\003\022\016\n\006weight\030\002 \001(" +
      "\005\022\023\n\013arrivalDate\030\003 \001(\t\022\016\n\006origin\030\004 \001(\t\022\014" +
      "\n\004type\030\005 \001(\t2\343\002\n\rAnimalService\022=\n\016findAn" +
      "imalById\022\033.google.protobuf.Int64Value\032\014." +
      "AnimalProto\"\000\022<\n\016findAllAnimals\022\026.google" +
      ".protobuf.Empty\032\020.AnimalListProto\"\000\022G\n\023f",
      "indAnimalsByOrigin\022\034.google.protobuf.Str" +
      "ingValue\032\020.AnimalListProto\"\000\022E\n\021findAnim" +
      "alsByType\022\034.google.protobuf.StringValue\032" +
      "\020.AnimalListProto\"\000\022E\n\021findAnimalsByDate" +
      "\022\034.google.protobuf.StringValue\032\020.AnimalL" +
      "istProto\"\000B(\n$slaughterHouse.grpc.protob" +
      "uf.animalsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_AnimalListProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimalListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalListProto_descriptor,
        new java.lang.String[] { "AllAnimals", "Code", });
    internal_static_AnimalProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnimalProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalProto_descriptor,
        new java.lang.String[] { "RegistrationNumber", "Weight", "ArrivalDate", "Origin", "Type", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
