// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animal.proto

package slaughterHouse.grpc.protobuf.animals;

public final class Animal {
  private Animal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalListProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalListProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014animal.proto\032\033google/protobuf/empty.pr" +
      "oto\032\036google/protobuf/wrappers.proto\"3\n\017A" +
      "nimalListProto\022 \n\nallAnimals\030\001 \003(\0132\014.Ani" +
      "malProto\"l\n\013AnimalProto\022\032\n\022registrationN" +
      "umber\030\001 \001(\003\022\016\n\006weight\030\002 \001(\005\022\023\n\013arrivalDa" +
      "te\030\003 \001(\t\022\016\n\006origin\030\004 \001(\t\022\014\n\004type\030\005 \001(\t2\343" +
      "\002\n\rAnimalService\022=\n\016findAnimalById\022\033.goo" +
      "gle.protobuf.Int64Value\032\014.AnimalProto\"\000\022" +
      "<\n\016findAllAnimals\022\026.google.protobuf.Empt" +
      "y\032\020.AnimalListProto\"\000\022G\n\023findAnimalsByOr",
      "igin\022\034.google.protobuf.StringValue\032\020.Ani" +
      "malListProto\"\000\022E\n\021findAnimalsByType\022\034.go" +
      "ogle.protobuf.StringValue\032\020.AnimalListPr" +
      "oto\"\000\022E\n\021findAnimalsByDate\022\034.google.prot" +
      "obuf.StringValue\032\020.AnimalListProto\"\000B(\n$" +
      "slaughterHouse.grpc.protobuf.animalsP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_AnimalListProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimalListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalListProto_descriptor,
        new java.lang.String[] { "AllAnimals", });
    internal_static_AnimalProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnimalProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalProto_descriptor,
        new java.lang.String[] { "RegistrationNumber", "Weight", "ArrivalDate", "Origin", "Type", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
